# Resource Quota
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ecommerce-quota
  namespace: shopeasy-dev
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 6Gi
    pods: "10"
    services: "5"
    configmaps: "10"
    secrets: "10"
    persistentvolumeclaims: "5"

---
# LimitRange
apiVersion: v1
kind: LimitRange
metadata:
  name: ecommerce-limits
  namespace: shopeasy-dev
spec:
  limits:
  - type: Container
    default:
      cpu: 300m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    max:
      cpu: "1"
      memory: 1Gi
    min:
      cpu: 50m
      memory: 64Mi
  - type: Pod
    max:
      cpu: "2"
      memory: 2Gi