{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secret
  labels:
    app: {{ .Values.backend.name }}
    tier: backend
type: Opaque
data:
  SECRET_KEY: {{ .Values.secrets.flaskSecretKey | b64enc }}
  DB_HOST: {{ printf "%s-mysql" .Release.Name | b64enc }}
  DB_PORT: {{ .Values.mysql.service.port | toString | b64enc }}
  DB_USER: {{ .Values.secrets.mysqlUser | b64enc }}
  DB_PASSWORD: {{ .Values.secrets.mysqlPassword | b64enc }}
  DB_NAME: {{ .Values.secrets.mysqlDatabase | b64enc }}
{{- end }}