{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql-secret
  labels:
    app: {{ .Values.mysql.name }}
    tier: database
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.secrets.mysqlRootPassword | b64enc }}
  MYSQL_DATABASE: {{ .Values.secrets.mysqlDatabase | b64enc }}
  MYSQL_USER: {{ .Values.secrets.mysqlUser | b64enc }}
  MYSQL_PASSWORD: {{ .Values.secrets.mysqlPassword | b64enc }}
{{- end }}