apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-backend-config
data:
  FLASK_DEBUG: {{ .Values.config.flaskDebug | quote }}
  SESSION_TYPE: {{ .Values.config.sessionType | quote }}
  SESSION_FILE_DIR: "/tmp/flask_sessions"