apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: session-store-pvc
  namespace: shopeasy-dev
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
