apiVersion: v1
kind: Pod
metadata:
  name: test-ebs-pvc-pod
  namespace: default
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "echo Test > /mnt/test && sleep 3600"]
    volumeMounts:
    - name: ebs-volume
      mountPath: /mnt
  volumes:
  - name: ebs-volume
    persistentVolumeClaim:
      claimName: test-ebs-pvc

