apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-backend
  namespace: shopeasy-dev
  labels:
    app: ecommerce
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecommerce
      tier: backend
  template:
    metadata:
      labels:
        app: ecommerce
        tier: backend
    spec:
      serviceAccountName: ecommerce-backend-sa
      containers:
      - name: backend
        image: 017820683847.dkr.ecr.us-east-1.amazonaws.com/ecommerce-app-backend:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 5000
        envFrom:
        - configMapRef:
            name: backend-config
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        volumeMounts:
        - name: flask-sessions
          mountPath: /tmp/flask_sessions
        startupProbe:
          httpGet:
            path: /api/health
            port: http
          failureThreshold: 30
          periodSeconds: 10
          initialDelaySeconds: 45
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/ready
            port: http
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 6
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /api/health
            port: http
          initialDelaySeconds: 90
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: flask-sessions
        persistentVolumeClaim:
          claimName: session-store-pvc
